### ISSUE TITLE
Tool additions to the new IP

### ISSUE THREAD

**Issue by UnsignedByte** [cornell-c2s2/c2s2_ip#6]
Things that should be added to the IP manager before we start working on it
- [ ] Linter to check formatting
  - [ ] Automated github action checking formatting on all files on push
- [ ] AutoFormatter
- [ ] Pymtl macro to run tests
  - [ ] Macro to run all tests
  - [ ] Macro to run tests for a specific IP only
  - [ ] Automated github action to run all tests on push
- [ ] Documentation on how to use tools
- [ ] Template directory with template IP
- [ ] Examples directory with some example blocks, tests, etc and thorough documentation
